Don't die if an int field is left blank.
Summary:
The last webpagetest run failed like so:
---
Traceback (most recent call last):
  File "./run_webpagetest.py", line 215, in <module>
    main()
  File "./run_webpagetest.py", line 207, in main
    url, test_id, dict_output)
  File "./run_webpagetest.py", line 155, in ConvertToDict
    mongo_dict[k] = int(dict_output[k])
ValueError: invalid literal for int() with base 10: ''
---

This change puts '0' there instead.  It's a bit sad because we can't
then distinguish between '0' inserted by the webpagetest, and '0'
inserted by us, but the alternatives seem worse.  We could do '-1',
which we would have to know to interpret as 'no data', or we could
just leave these fields as strings instead of integers, which makes
them harder to manipulate from within mongo-db.

Test Plan: None

Reviewers: chris, alpert

Reviewed By: alpert

Differential Revision: http://phabricator.khanacademy.org/D883