Remove TopicVersion from gae_download.json, making this error during gae_download.py's execution go away: Do I need to do any other work downstream, or will the queries just notice that TopicVersion is missing from the download and skip it?
Summary:
107.21.59.74 - - [28/May/2013:14:57:50 -0700] "GET /api/v1/dev/protobuf/TopicVersion?index=backup_timestamp&oauth_nonce=69235459366911319102&oauth_timestamp=1369778264&dt_end=2013-05-26T20%3A30%3A00Z&max=1000&oauth_consumer_key=4rFmvSXgK7aDxfLY&oauth_signature_method=HMAC-SHA1&dt_start=2013-05-26T20%3A00%3A00Z&oauth_version=1.0&oauth_token=6yJbZ8HALqBNCyXZ&oauth_signature=I8W3UJ86i%2B%2FYBCXFiQdvubfqLvw%3D HTTP/1.1" 500 234 - "Python-urllib/2.7" "www.khanacademy.org" ms=1876 cpu_ms=130 cpm_usd=0.000026 app_engine_release=1.8.0 instance=00c61b117cca6729d962df9a53edb7377303aa
D 2013-05-28 14:57:50.250
Built signature: I8W3UJ86i+/YBCXFiQdvubfqLvw=
E 2013-05-28 14:57:50.424
No implementation for kind 'TopicVersion'
Traceback (most recent call last):
File "/base/data/home/apps/s~khan-academy/0523-ee2c21b4859e.367585559472067655/api/route_decorator.py", line 151, in api_errors_formatted
return func(*args, **kwargs)
File "/base/data/home/apps/s~khan-academy/0523-ee2c21b4859e.367585559472067655/api/auth/decorators.py", line 248, in wrapper
return func(*args, **kwargs)
File "/base/data/home/apps/s~khan-academy/0523-ee2c21b4859e.367585559472067655/api/decorators.py", line 181, in pickled
result = func(*args, **kwargs)
File "/base/data/home/apps/s~khan-academy/0523-ee2c21b4859e.367585559472067655/api/v1_misc.py", line 532, in protobuf_entities
query = db.GqlQuery(query_string)
File "/python27_runtime/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2701, in __init__
model_class = class_for_kind(self._proto_query._kind)
File "/python27_runtime/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 296, in class_for_kind
raise KindError('No implementation for kind \'%s\'' % kind)
KindError: No implementation for kind 'TopicVersion'

Merge branch 'master' into remove_topic_version

Test Plan: 1. None, since this should just skip the entity

Reviewers: jace

Reviewed By: jace

Differential Revision: http://phabricator.khanacademy.org/D2464